name: web_project
dependencies:
- nose=1.3.7=py27_0
- openssl=1.0.2j
- pip=8.0.2=py27_0
#- python=2.7
#- readline
- setuptools=19.6.2=py27_0
- sqlite
- tk
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - web.py==0.37

